[app]
version      = "0.1.0"
display_name = "Hello world"
description  = "Says hello!"
source       = "github:nepthar/harbor/main/apps/hello-world.happ"

[run.main]
image  = "alpine:latest"
cmd    = ["/bin/sh", "-c", "echo \"hello world!\"; echo; env; echo"]
restart = "no"
